### ISSUE TITLE
home page needs a banner

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#13]
https://ccdhportaldev.pedscommons.org/

Banner that says: Center for Cancer Data Harmonization (CCDH) or a tag line that summarizes our work

**Comment by nicolevasilevsky** [comment]
add to future internal meeting agenda

**Comment by nicolevasilevsky** [comment]
We discussed tag lines on internal call on 08/05. _In progress_

**Comment by nicolevasilevsky** [comment]
Is this still needed? Seems like less of a priority, I think we should close.

**Comment by mellybelly** [comment]
Did we get a tagline? I don't see one, how about:
Bringing harmony to cancer data across the CRDC

**Comment by nicolevasilevsky** [comment]
We had not agreed on a tagline yet. Your suggestion sounds good!

@jen-martin or @bfurner could you add this to the home page?

**Comment by nicolevasilevsky** [comment]
pinging @jen-martin and @bfurner

**Comment by jen-martin** [comment]
I can add a site "slogan"  via Administration >> Configuration >> System >> Site Details, but I can't seem to find where to finesse the styling. The quick-and-dirty solution would be to edit the header graphic that has the NIH logo so that the tagline is below it. However, I'm not sure that editing the logo graphic is allowed. Any suggestions @bfurner ?

**Comment by nicolevasilevsky** [comment]
I agree that we probably can't edit the NIH logo. 

Thanks for looking into this @jen-martin. I am not sure how critical this is, if you are not able to find a nice solution, then I think we can probably close this ticket.

**Comment by jen-martin** [comment]
Spoke too soon. I'm working on it now, finessing the layout. Any suggestions for styling?

**Comment by nicolevasilevsky** [comment]
maybe italics?

**Comment by jen-martin** [comment]
Changed the font to italics, and the font color to grey. This block is quite customizable (for example: background color, height, font characteristics, etc.) so let me know if there's any other suggestions.

**Comment by nicolevasilevsky** [comment]
I think it looks good! I think we can close this, unless you would prefer to wait for more feedback
