### ISSUE TITLE
add DMH info to Standards and Tooling page

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#15]
https://ccdhportaldev.pedscommons.org/standardsTooling

**Comment by nicolevasilevsky** [comment]
include tool evaluation that Jim did?

**Comment by nicolevasilevsky** [comment]
@balhoff @bfurner @mbrush - do you want to add info about the DMH to this page?
https://ccdhportaldev.pedscommons.org/standardsTooling

or should we close this ticket?

**Comment by bfurner** [comment]
We should include:

FHIR [link](http://hl7.org/fhir/)
The FHIR (Fast Healthcare Interoperability Resources) Specification is a standard for exchanging healthcare information 

BRIDG [link](https://bridgmodel.nci.nih.gov/)
The goal of the Biomedical Research Integrated Domain Group (BRIDG) Model is to produce a shared view of the dynamic and static semantics for the domain of basic, pre-clinical, clinical, and translational research and its associated regulatory artifacts.

**Comment by nicolevasilevsky** [comment]
@bfurner I updated the table, let me know if any changes are needed

**Comment by decorons** [comment]
Probably unrelated to this ticket, but on the list of Ontologies, etc. , do you want to add a note for people to contact you or come to (to be established) general office hours to discuss?  [For instance, the lists don't really tell you who uses the standard under what circumstances.  You don't have time to create that kind of info now, but over time you might.  In the meantime, you might be able to provide additional verbal guidance.  For instance, CDISC aligned standards are used by NCI Clinical Trials for new trials.  We have SI staff who could provide additional info/ guidance/ context beyond what's on the CDISC website.]

**Comment by nicolevasilevsky** [comment]
Good idea, Sherri!

**Comment by nicolevasilevsky** [comment]
I added contact info on this page: https://ccdhportaldev.pedscommons.org/standardsTooling

**Comment by nicolevasilevsky** [comment]
closing this - reopen if still needed

**Comment by decorons** [comment]
Hi all,
The CRDC Ecosystem page text seems like it could use a little refining, but I’m not sure what to suggest as a change –  Thanks, Sherri

The CCDH seeks to build a community of nodes and resources that will find agreement and leverage their expertise to match and extend existing data models across resources, understanding their requirements for data annotation, harmonization, navigation, and quality assurance. The Community Development group acts as the facilitator and provides support and coordination to the community.
