### ISSUE TITLE
create a page: Presentations

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#16]
- [x] run this idea by NCI / get approval
- [x] link out to past presentations (embed the google slides into the Drupal website or embed a PDF)
- [x] link out to recordings from past presentations

**Comment by volcs0** [comment]
Discussed with NCI/FNL - need better name than community outreach - OK to have materials of "general interest" - e.g., data model presentation

**Comment by nicolevasilevsky** [comment]
@jen-martin can you create a new page that is called something like 'Presentations' (not sure if this is a better name, but this is the content that we plan to add).

I'll add links to the slides and recordings once the page is up.

Thanks!

**Comment by nicolevasilevsky** [comment]
@monicacecilia can you point me to the google folder with the slides and recordings?
Should we move these somewhere more permanent that google drive? maybe add them to zenodo or something like that?

**Comment by jen-martin** [comment]
Added a blank page here: [https://ccdhportaldev.pedscommons.org/presentations](https://ccdhportaldev.pedscommons.org/presentations)
Let me know if you want the menu link moved; it is currently under About.

**Comment by nicolevasilevsky** [comment]
@jen-martin I added some content. Can you embed the slides and recordings into Drupal?

**Comment by nicolevasilevsky** [comment]
I will add the slides to Slide Share.

**Comment by nicolevasilevsky** [comment]
done
