### ISSUE TITLE
add content: Relevant Ontologies and Standards

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#19]
Please add the list of relevant ontologies and standards to the Web Portal on the Standards and Tooling page:
https://ccdhportaldev.pedscommons.org/standardsTooling

See list here:
https://docs.google.com/spreadsheets/d/1PTSPbl9O-bR_jSjEIIddxXZnA3lLFi0Y7qYbc9RZ6Eo/edit#gid=1563530612

Please ignore the ontologies/standards that lack additional info, such as QIBA, line 26

Let me know if you need help/more info

**Comment by nicolevasilevsky** [comment]
Could we have a search box like on OLS?
https://www.ebi.ac.uk/ols/ontologies

Maybe a page with something like this OLS page?

**Comment by nicolevasilevsky** [comment]
There is some initial content added here:
https://ccdhportaldev.pedscommons.org/standardsTooling

Should we add additional info to the ontologies table?
Like a column with domain?

@mellybelly @hsolbrig @jiaola

**Comment by nicolevasilevsky** [comment]
Note - I need to finish adding descriptions for each ontology.

question - most of this text is verbatim from another site - is that okay? or should we reword it? or quote it? Or should we have a standardized description like:
[X] ontology/terminology is used to describe and classify information about [X].

**Comment by gaurav** [comment]
For some standards, we know about useful resources aside for the official documentation. Is there a good way to add that to the website? For example, for the Portable Format for Biomedical Data (PFB), the closest thing to an official specification is the [Github repository for their Python library](https://github.com/uc-cdis/pypfb), but CBIIT has a really good write-up of this format in their [Bento Meta DB repository](https://github.com/CBIIT/bento-meta/tree/feat-pfb/python/bento_meta/pfb#portable-format-for-bioinformatics). Currently we only have [a single link for each resource](https://docs.google.com/spreadsheets/d/11agxuj1o-pi9GlpRam2C9ieCaWw-dcKxIcUMe1wPfmo/edit#gid=0), but should we look into supporting multiple links in some way that won't look too messy?

**Comment by nicolevasilevsky** [comment]
@jen-martin can you implement multiple links for the resources/standards?

**Comment by jen-martin** [comment]
@gaurav and @nicolevasilevsky  Would something like adding this line of text to the description work: "Other documentation resources: [CBIIT Bento Meta DB Readme](https://github.com/CBIIT/bento-meta/tree/feat-pfb/python/bento_meta/pfb#portable-format-for-bioinformatics)."

**Comment by gaurav** [comment]
That looks great to me! Something like "The [CBIIT Bento Meta DB Readme](https://github.com/CBIIT/bento-meta/tree/feat-pfb/python/bento_meta/pfb#portable-format-for-bioinformatics) has a good description of this format." would also work.

**Comment by gaurav** [comment]
I liked Nicole's suggestion of being able to search in the tables provided. I think something like https://www.w3schools.com/howto/howto_js_filter_table.asp could be pretty useful if it can be implemented in Drupal.

**Comment by nicolevasilevsky** [comment]
that looks great @gaurav!

**Comment by nicolevasilevsky** [comment]
I am going to close this ticket since the main work is done and I'll create a new ticket to enhance this table, if possible, which is lower priority.
