### ISSUE TITLE
create a CDA / CCDH Engagement Plan

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#2]
See draft [here](https://docs.google.com/document/d/1FxsDLTBKA07A0zYvEDONb-JGOHhUWsA_Hm70sHtI37I/edit)

- [x] initiate communication with their operations team
- [x] have initial scoping meeting to discuss collaboration; determine ongoing meeting schedule (include CCDH leads, CDA leads, NCI leadership)
- [x] have technical scoping meeting following initial meeting (attendees TBD)

**Comment by nicolevasilevsky** [comment]
Technical meetings were held on:
2020-08-13 - Discussed the scope for the initial phase of work between CDA and CCDH
2020-08-27 - Discussed Time-series data and MVP
2020-09-10 - Discussed the proposed MVP

**Comment by nicolevasilevsky** [comment]
can this be closed?

**Comment by monicacecilia** [comment]
I think we can close it. The tasks we set out to complete for this ticket have been completed. The engagement with CDA will continue throughout the life of the project, but this ticket can be closed. 
Thank you @nicolevasilevsky
:bowtie:
