### ISSUE TITLE
Move WS descriptions to a single page with brief explanation for each WS

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#24]
@jen-martin Move workstream descriptions to a single page with brief explanation for each workstream.

@balhoff 
@volcs0 
@hsolbrig 
@cgchute 
@monicacecilia 
@mellybelly 

We need to provide brief explanations of each WS: please see draft content here: https://ccdhportaldev.pedscommons.org/ccdhWorkstreams

**Comment by nicolevasilevsky** [comment]
Here is some text from a talk, we could use this as a starting place):

1.    Community development (lead: Volchenboum; co-lead Vasilevsky) 
Communities served include the CRDC nodes, bioinformatician and clinician researchers, and data and biospecimen collectors/aggregators/contributors. This workstream functions to interact with community members in various contexts—workshops, online forums, issue tracking, and through personal communications (e.g, “concierge services”). The workflows and needs requirements of these groups will be documented and matched with other CCDH workstreams to ensure prioritization, solution planning and documentation, and stakeholder communication. Various concierge services will be provided through multiple modalities. Web portal and content will be designed and deployed and user testing will be coordinated.
2.    Data Model harmonization (lead: Chute). 
Performs landscape analysis on the diversity of relevant data models, including those implemented already within the CRDC nodes as well as those commonly used within the external community (e.g. FHIR, BioLink model). Responsible for prioritizing aspects of the models to be harmonized and designing the harmonization plan and the ongoing evolution of the CRDC-H. Supports Commons node implementation of the CRDC-H.
3.    Ontology and terminology ecosystem (lead: Solbrig and TBN Senior Knowledge Graph & Ontology Architect). 
Provides computational access and user navigation to relevant terminologies, and supports content development and terminological extension. Provides algorithmic support for equivalency determination and best practices in the use of terminology mappings. Supports community development environment using standardized design patterns. 
4.    Tools and Data Quality (lead: Balhoff). 
Develops tools and models for applying structured metadata to data being submitted to the CRDC nodes, leveraging and extending existing metadata standards and building upon ongoing work in the Data Model Harmonization and Terminology services teams. Supports biocuration SOPs and best practices, and develops quality assurance unit tests.
5. Program Management and operations (lead: Haendel, co-lead McMurry). A community resource of this magnitude and complexity requires robust project management. This workstream supports all the others, documents program progress, and maintains robust interaction with Leidos program staff. Supports personnel work tracking, integrated into daily processes to ease reporting burdens and increase communication and collaboration.

**Comment by jen-martin** [comment]
The new page is here: [https://ccdhportaldev.pedscommons.org/ccdhWorkstreams](https://ccdhportaldev.pedscommons.org/ccdhWorkstreams)

**Comment by jen-martin** [comment]
Added the suggested content above

**Comment by nicolevasilevsky** [comment]
I think this can be closed, please reopen if necessary
