### ISSUE TITLE
rename labels for contact us?

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#27]
https://ccdhportaldev.pedscommons.org/about

Contact us is on the header.

Should the labels be revised? (Email and Public Slack Channel)

**Comment by nicolevasilevsky** [comment]
related to #23

**Comment by decorons** [comment]
Is any explanatory information about the SLACK channel needed? Or will everyone just know what to do?

**Comment by nicolevasilevsky** [comment]
good point, probably not! I'll make myself an action item to add some additional content/instructions

**Comment by nicolevasilevsky** [comment]
> Is any explanatory information about the SLACK channel needed? Or will everyone just know what to do?

done

**Comment by nicolevasilevsky** [comment]
I think this ticket can be closed, please reopen if necessary
