### ISSUE TITLE
fix links to email

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#29]
@jen-martin The link outs to the email address aren't working on these two pages:

https://ccdhportaldev.pedscommons.org/standardsTooling - where it says contact us (I did something wrong, can you please fix?)

and

https://ccdhportaldev.pedscommons.org/support - where is has our email address

**Comment by jen-martin** [comment]
Done. Modified links so they are formatted as "mailto:centerforcancerdh@gmail.com"

**Comment by nicolevasilevsky** [comment]
thanks! I thought I did that and it didn't work, I have done something wrong.
