### ISSUE TITLE
create/disseminate Q3 newsletter 

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#3]
- [ ] @keblumhardt draft newsletter
- [ ] share with program leads
- [ ] send to community via email and Slack

**Comment by nicolevasilevsky** [comment]
@keblumhardt @monicacecilia this seems like low priority, I think. But the end of this quarter is in a couple weeks, should we get this out by then?

**Comment by keblumhardt** [comment]
@nicolevasilevsky @monicacecilia yes, I think we should start working on it. Is there something we could feature for a story? I am happy to write up a draft. We can also discuss at CD meeting on Monday.

**Comment by nicolevasilevsky** [comment]
Maybe we should highlight the office hours and concierge services? Although they are getting weekly emails about that. I don't know if I have any other ideas.
