### ISSUE TITLE
Add more content to CRDC Ecosystem webpage

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#32]
@decorons suggested in #15 that we improve the CRDC Ecosystem webpage.

I added descriptions of each node: https://ccdhportaldev.pedscommons.org/crdcEcosystem

Note- I borrowed text from here and other websites: https://datascience.cancer.gov/data-commons/repositories

Any other suggestions?

**Comment by decorons** [comment]
Hi thanks,
I like the descriptions, but I was more asking about the initial paragraph, which seems to need some tweaking.

The CCDH seeks to build a community of nodes and resources that will find agreement and leverage their expertise to match and extend existing data models across resources, understanding their requirements for data annotation, harmonization, navigation, and quality assurance. The Community Development group acts as the facilitator and provides support and coordination to the community.

Thanks, Sherri

**Comment by nicolevasilevsky** [comment]
Ah, I see. 

Can anyone suggest revisions to this paragraph:

The CCDH seeks to build a community of nodes and resources that will find agreement and leverage their expertise to match and extend existing data models across resources, understanding their requirements for data annotation, harmonization, navigation, and quality assurance. The Community Development group acts as the facilitator and provides support and coordination to the community.

**Comment by monicacecilia** [comment]
Updated paragraph (contributions from @mellybelly and I). :bowtie: 

"The CCDH provides leadership and guidance to the CRDC community in data model harmonization as well as terminological use and development. Our team is creating a common data model that is harmonized for use across NCI’s nodes and resources. The foundation of this work will entail reaching an understanding of their requirements for data annotation, harmonization, navigation, and quality assurance. The Community Development workstream acts as the facilitator and provides support and coordination to the community."

**Comment by nicolevasilevsky** [comment]
I updated this page: https://ccdhportaldev.pedscommons.org/crdcEcosystem

**Comment by nicolevasilevsky** [comment]
I will close, please reopen if necessary.
