### ISSUE TITLE
combine table on Standards and Tooling page

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#33]
@jen-martin can you please combine the tables into one table the Standards and Tooling page?
https://ccdhportaldev.pedscommons.org/node/3

**Comment by monicacecilia** [comment]
@jen-martin @nicolevasilevsky - this looks fantaaaastic! 🎉 
- I just noticed that there is not a link to Ptolemy (is that intended?)

**Comment by nicolevasilevsky** [comment]
> I just noticed that there is not a link to Ptolemy (is that intended?)

yes

**Comment by nicolevasilevsky** [comment]
This is done, thanks @jen-martin!
