### ISSUE TITLE
web portal changes needed

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#35]
Per Sherri:

- [x] standards and tooling table should have NCIt and NCIm as abbreviations, she is checking with Lyuba to verify (I see also that NCIt is shown in section beneath with abbreviation).
 
- [x] need a better description for Ptolemy.V @gaurav could you write this? Here is some text to get you started: Ptolemy matches variables and values, (not just values) – and also, it is configured to work with caDSR at present, but the tool itself doesn’t inherently require use of caDSR.  You can match source to any target that you load.  That’s important for people to know I think. (e.g. a node might want to use it to match to its own data dictionary, even though it is not using caDSR CDEs.).  I don’t know how best to word it, though, and Gaurav has hands on experience. 

 
- [x] make links open in a new page

**Comment by gaurav** [comment]
How's this:
"A closed-source tool for mapping columns in datasets to common data elements from sources such as the caDSR. For enumerated fields, users can use a drag-and-drop interface to harmonize values in datasets to permitted values specified in the data element. Currently in a closed pilot."

@balhoff What do you think?

**Comment by balhoff** [comment]
That sounds good to me.

**Comment by nicolevasilevsky** [comment]
Thanks Gaurav and Jim! I updated the website:
https://ccdhportaldev.pedscommons.org/standardsTooling
