### ISSUE TITLE
Add content to Standards and Tooling page

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#37]
From Sherri:
Add how the list (1) how it is ‘curated’; (2) what users might expect to find here in the future –
Such as guidance on when to consider using something for what – and (3) later on, any Recommendations or Requirements for standards use by CRDC.

**Comment by nicolevasilevsky** [comment]
pinged tools workstream on Slack on 01/26/21

Should be discussed on an internal call

**Comment by monicacecilia** [comment]
@nicolevasilevsky - if you'd like, please add this to next week's agenda. Thank you! 😉

**Comment by nicolevasilevsky** [comment]
https://ccdhportaldev.pedscommons.org/standardsTooling

**Comment by monicacecilia** [comment]
Dupe of #49 - closing this one.
