### ISSUE TITLE
feedback from NCI team re: web portal

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#38]
-  [x] The information is overlapping for “CCDH Team and Organization” and “Workstreams” pages. Is there a way to combine them?  Since many members overlap in workstreams, is it better to list all the team members and indicate which workstreams that they are part of?
- [x] e.g. have one table for the members following the Leads and the Workstream description all on one page
- [x] We don’t need to list names of program oversight

## CRDC Ecosystem

- [x] Do we need CRDC ecosystem? A link to the https://datacommons.cancer.gov website may be sufficient. 
- [x] If we keep this, then it should: (i) reflect all the CRDC components as on the data commons website as above, (ii) CRs and other nodes (e.g. CDS) should be added, and (iii) HTAN and KF removed.
- [x] HTAN is not part of the CRDC Ecosystem. DCCs should not be listed as part of the CRDC ecosystem as there are many DCCs in addition to HTAN that contribute to CRDC. 

## Project timeline
- [X] Fonts are small in the project timeline box. 
- [x] Can more details be added to the table?
- [x] Will a link to the Project Tracker with details on the plans/timelines (currently under development on GitHub) replace this table?

## Standards and tooling

- This page we assume will substantially evolve in the near future?
- At this point it seems like a list of resources rather than recommendations. And it doesn’t offer useful detail such as guidance on when you would consider using X, for what) – the hope would be that potential users of ICD-10 (terminology) or OL (terminology server) for instance, might talk with CCDH to learn more.
- It would be also useful to think more about how to present the categorization, and how it could be customized for CRDC use.
- [x] The description mentions a “curated list”, however it is not clear who has curated it.
- [x] How does the portal facilitate concierge services and two-way communication?

## FAQs 

- [x] Will there be more FAQs listed here when the website goes public? How will they be populated?
- [x] Overall the content is pretty light, but preferable to have this infrastructure and presence that can be frequently updated. Including details on some of the major activities will be good e.g. data model development/status.

**Comment by jen-martin** [comment]
I reformatted the Phase 1-Phase 4 timeline graphic into an HTML table to make the fonts easier to read. I also inserted the summary/overview for each phase into the table. If the summary/overview works better as paragraphs, let me know. I saved the original text (hidden behind comment tags) in case the original is more desirable. 
Also, if there are better colors for the table, I can change that; I just copied the color scheme from the original graphic.
If there is additional detail you want in the table, that can now be added more easily.

**Comment by monicacecilia** [comment]
WRT CRDC Ecosystem: we now have an updated document with information about CRDC structure. I suggest that we update the contents of this page https://ccdhportaldev.pedscommons.org/crdcEcosystem with what's on the document that Fed Oversight team prepared.

**Comment by monicacecilia** [comment]
WRT Project Timeline: 
- Yes, the [Project Tracker page](https://cancerdhc.github.io/) will eventually replace the timeline currently available on https://ccdhportaldev.pedscommons.org/timeline - and it will contain more detail.

**Comment by monicacecilia** [comment]
WRT Standards & Tooling: 

> This page we assume will substantially evolve in the near future?

Yes, it will. 

> At this point it seems like a list of resources rather than recommendations. And it doesn’t offer useful detail such as guidance on when you would consider using X, for what) – the hope would be that potential users of ICD-10 (terminology) or OL (terminology server) for instance, might talk with CCDH to learn more.

It is indeed a list of resources. We don't yet have available tools created by the CCDH team to recommend, however, we believe it is important to offer as much information to the community as we can - given what is currently available. 


> It would be also useful to think more about how to present the categorization, and how it could be customized for CRDC use.

Sure. we'll have a think about updating the categorization. your suggestions are welcome!

> The description mentions a “curated list”, however it is not clear who has curated it.

The list is the result of the combined efforts from the participants in the Semantic Strategies workshop, as well as members of the CCDH Workstreams. Should we add these details?

> How does the portal facilitate concierge services and two-way communication?
