### ISSUE TITLE
Review and update workstream membership on web portal

### ISSUE THREAD

**Issue by bfurner** [cancerDHC/community-development#41]
Resham noted that there seem to be some mistakes in where individuals are placed in workstreams on our web portal's "Team" page [here](https://harmonization.datacommons.cancer.gov/ccdhTeamOrganization) 

The issues appear in the table on that page.  For example, Sam Volchenboum is listed under "Data Model Harmonization", Chris Chute is *not* listed under "Data Model Harmonization", etc.

**Comment by nicolevasilevsky** [comment]
I updated this page:
https://ccdhportaldev.pedscommons.org/ccdhTeamOrganization

Please reopen if more changes are needed
