### ISSUE TITLE
CCDH website: Create new page to discuss CRDC-H, Terminology Services, and Validation Tool(s)

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#43]
https://cancerdhc.github.io/ccdhmodel/

as part of our documentation

**Comment by bfurner** [comment]
Where should this information go?

**Comment by nicolevasilevsky** [comment]
I'm not sure. @bfurner I wasn't on the last internal call, was there any discussion about where to house the documentation for this project? Is it going to be in GitHub and then linked from the website?

cc @monicacecilia

**Comment by dvenckusuchgo** [comment]
Pages have been created under "CCDH Resources" top menu, awaiting content.

**Comment by dvenckusuchgo** [comment]
Refer to gh-46

**Comment by keblumhardt** [comment]
Terminology content:
- [ ] Introductory information blurb
- [ ] Add documents to be included

**Comment by monicacecilia** [comment]
All documentation is being captured [here](https://docs.google.com/document/d/16_HE_2ciDPJstd75ivbUTL22Sez-WGOBA6anT9qUoKM/edit#).

**Comment by monicacecilia** [comment]
This ticket may still be quite volatile - the way the documentation is growing may have an impact on content organization. We may need to rethink our ‘merged’ state… 😞  
We will need to capture a lot of information, so instead of splitting content by workstream, we may need to group  / organize the content by subject. 
Though I can see making an argument for keeping everything on the same page, maybe what we can do is utilize some visual cue to let the user know ‘here’s a break’ — a thick bar in the middle of the page, a figure? And in the future, one of the banners from the 'homepage restyling' examples.

**Comment by nicolevasilevsky** [comment]
I think a thick bar in the middle of the page makes sense

**Comment by monicacecilia** [comment]
Dear @dvenckusuchgo and @jen-martin , content is now ready and stable. Please post to CCDH website and GH page as appropriate at your earliest. 🌷 
Thank you!

**Comment by dvenckusuchgo** [comment]
Content updated (Production & ccdhportaldev)

**Comment by dvenckusuchgo** [comment]
Some of the graphics should be revised at a later time.  They will be difficult to read on smaller screens.

**Comment by monicacecilia** [comment]
Thank you @dvenckusuchgo! This is brilliant. 

Just a handful of touch up points:
- [ ] please remove figure and legend for 'The role of CCDH in the wider CRDC environment.'
- [ ] please revise headings levels as explained in source Google doc
- [ ] please trim the figure in the section 'Creating NCI Thesaurus (NCIt) interoperability: NCIt-Plus' to remove figure legend (which is part of the figure) reading: 'Figure 16: Consolidated Data Description' - to reflect how the image appears in the Google document. 
- [ ] Yes, that 'LinkML image is not very good. 😞 -- @hsolbrig @jiaola - any chance you can provide a better figure, or a higher res of the figure labeled as 'Figure: LinkML incorporates ISO/IEC 11179-3 meaning/data model' [in this page](https://harmonization.datacommons.cancer.gov/ccdh-resources)?

**Comment by dvenckusuchgo** [comment]
Changes applied to Production + ccdhwebdev
