### ISSUE TITLE
CCDH Website Edits from NCI/FNL (2021-02-14)

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#44]
From Resham:
CCDH Web portal: https://harmonization.datacommons.cancer.gov/

~~- [ ] Add details on the Harmonized model (CRDC-H). And emphasize the Concierge Services – the service is listed but buried under several links and not well explained. @bfurner~~ | Details about request are now in #43 and #47 

~~- [ ] Consider rewording: Under About CCDH, “The NCI’s Center for Cancer Data Harmonization (CCDH) aims to create a national cancer data ecosystem" however this is the job of the CRDC. Similar for “CCDH relies on the community of NIH cancer nodes" where it should be CRDC nodes.  @bfurner or @jen-martin _(I see this on this page (https://harmonization.datacommons.cancer.gov/) but not our dev webpage, so I don't know how to fix this)_~~ | This request is now in #45 

~~- [x] There is no connection between the graphic and the text – make the link from the graphic to the text. @jen-martin or @bfurner~~ | This request is now in #50

~~- [ ] The office hours does not specify how to join it. Should be made more obvious that is a virtual meeting, and that link and instructions are sent to CRDC members. @monicacecilia should we remove this?~~ Outdated. 

~~- [x] The "support" link should be called "concierge"? @jen-martin~~ | This request is now in #47 

Minor bugs:

- [x] found  error on the "About us >> presentations” site, the bottom has the error message “This block is broken or missing. You may be missing content or you might need to enable the original module.’ @jen-martin 

~~- [x] The "About us" -> CRDC leaves the page, so it's a little jarring .. Should say something like "external" or "back to.." @jen-martin~~  | This request is now in #50

FAQ

~~- [ ] about Portal - what does it mean, how is the portal different than the existing site? @monicacecilia should we remove this?~~ cannot find `about portal` text, so scratching this off. 

~~- [ ] FAQ about data model but the site overall has nothing on the CRDC-H data model. @bfurner~~ | This topic now addressed in #52

~~- [ ] Recommend adding contact info to the lower third to be more easily accessible @jen-martin~~ | This issue is being addressed in #51 

Support page contact information

- [x] listserv going to google group – remove for now, we can create a list serve at NIH – this can have non-NIH addresses @jen-martin 
- Using Gmail – no issues at this time, but when NCI takes over the email will be changed; we can also look at the option to have apps support group to forward emails to CCDH contacts

**Comment by jen-martin** [comment]
How do you want the link to the CRDC Ecosystem changed, and should it be placed elsewhere in the menu?

Is "CRDC Ecosystem [external]" what folks had in mind for this?
Should it stay where it is in the menu, or perhaps be moved to the bottom of the list of items, or elsewhere in the menu?

**Comment by jen-martin** [comment]
Which contact information should go in the footer, the email address or slack link? Or, should a separate Contact page be created with both links?

**Comment by nicolevasilevsky** [comment]
@jen-martin these are requests from Resham, could you please ask her for clarification? Do you have her email?

**Comment by nicolevasilevsky** [comment]
> Which contact information should go in the footer, the email address or slack link? Or, should a separate Contact page be created with both links?

I interpret this is as adding a contact us link in this space below. There already is a separate contact us page, right? Maybe just create another link at the bottom of the page that links to that? Again, I think Resham will be able to better clarify though.

Thanks for doing this, @jen-martin!

![image](https://user-images.githubusercontent.com/6722114/113021657-a8231680-9138-11eb-9f99-2288d7bde4c6.png)

**Comment by jen-martin** [comment]
@nicolevasilevsky: No, we currently don't have a separate Contact Us page. The "Contact Us" menu item is a mailto:centerforcancerdh@gmail.com link rather than a stand-alone page.

I'll ask Resham for clarification.

**Comment by bfurner** [comment]
adding @dvenckusuchgo to this so she is aware

**Comment by monicacecilia** [comment]
@jen-martin @dvenckusuchgo 👀  ⬆️

**Comment by monicacecilia** [comment]
@jen-martin - please se #45 for details about updating text for the introduction in the landing page.

**Comment by monicacecilia** [comment]
Some updates from @jen-martin's brilliant work: 
- we now have a Contact Us page. 🎉 
- footer is better laid out. Still need to add link to `Contact Us` page, see #51

**Comment by monicacecilia** [comment]
The items in this ticket have been replaced with #45, #46, #47, #48, #49, #50, #51, and #52
Closing to avoid redundancy.
