### ISSUE TITLE
CCDH Website: Edit intro text in landing page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#45]
URL: https://harmonization.datacommons.cancer.gov/

What To Do:
- [x]  Replace all the text with the following: 

The CCDH serves three main roles within the Cancer Research Data Commons (CRDC) ecosystem:
- Facilitate retrospective and prospective semantic harmonization of data across nodes of the CRDC.
- Coordinate the community to ensure quality “fit for purpose” design and implementation of standards that will facilitate interoperability of heterogeneous data types and CRDC resources
- Find agreement across the communities built around CRDC, including matching and extending data models, determining annotation and harmonization and building quality assurance resources.

**Comment by nicolevasilevsky** [comment]
I updated this:
https://ccdhportaldev.pedscommons.org/node/14

Reassigning to @DaveraGabriel for review

**Comment by dvenckusuchgo** [comment]
@monicacecilia I'm looking at 3 paragraphs of text on the front page. Was ALL text in the body of the front page to be replaced with this 1 paragraph/bullet-points above the graphic?

**Comment by dvenckusuchgo** [comment]
Would something like this work...
[https://drive.google.com/file/d/1onWavbTH2f--YkUNaY0noW-V2tDHP14u/view?usp=sharing](CCDH - Three Main Roles)

**Comment by monicacecilia** [comment]
[Here](https://docs.google.com/presentation/d/1qcUO98MWqM0OkosQbaYBng9ybySEXYCUYrIjrtBIJMo/edit#slide=id.g632248c723_0_15) are some graphics we could use.

**Comment by dvenckusuchgo** [comment]
There's not enough time to work in the graphics.  I made the content changes, but we're going to have to bump the home page design changes to Phase 3.  By then I'll have the theming problem corrected.
Also: gh-57, gh-55
