### ISSUE TITLE
CCDH Website: Update TopLevel Menus

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#46]
URL: https://harmonization.datacommons.cancer.gov/

What to do: 
- [x] Create TopLevel Menu `CCDH Resources`  with the following submenus:   
~~- CRDC-H~~
~~- Terminology/codeset services~~
~~- Tools to validate and transform data~~

- [x] Change TopLevel Menu `Standards and tools`  to  `Additional resources`

**Comment by nicolevasilevsky** [comment]
I am unassigning myself b/c I don't know how to do these things and I don't want to mess up the site!

**Comment by dvenckusuchgo** [comment]
Menu items revised and corresponding pages added as placeholders.

**Comment by dvenckusuchgo** [comment]
Waiting for content.  The menus/pages exist, but are hidden until we have content to deploy.

**Comment by dvenckusuchgo** [comment]
Refer to gh-43

**Comment by monicacecilia** [comment]
- Please change this: keep only Top Level Menu, no submenus, and keep the page at /ccdh-resources
- Documentation can be found [here](https://docs.google.com/document/d/16_HE_2ciDPJstd75ivbUTL22Sez-WGOBA6anT9qUoKM/edit#heading=h.vnuhpxuwxywn).
- Figure was part of our slides, [here](https://docs.google.com/presentation/d/1q_DNECDZvg2DP1YMf11YEyiMhr3wdK10kwExDA2WbnE/edit#slide=id.gc7fc2f4315_0_4).

**Comment by dvenckusuchgo** [comment]
Requires a code update
