### ISSUE TITLE
CCDH Website: Update information in 'Concierge' page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#47]
URL: https://harmonization.datacommons.cancer.gov/support

What To Do: 
- [x] Update TopLevel Menu to `Concierge` to replace current `Support` menu.
- [x] Make the role of CCDH clearer. That is, add text explaining that the tools we create and the support we provide are NOT directly harmonizing. Rather, we provide the tools and services to empower end users to do so. 
- [x] Add a link to information (new page being created) about the Harmonized model (CRDC-H). #43 
- [x] Emphasize the Concierge Services by adding text to reference our Support Service Engagement Plan, and add a link to it. [_NV: I added mention of this, we can add a link to it when it is done_]
- [x] Remove information about Office Hours, and add information about _Homing in on Harmonization_ sessions.
- [x] Merge information from the `Contact Us` page into the `Concierge` page. The information should read:
  - _Contact Us_
  _EMAIL - Contact us by email at centerforcancerdh@gmail.com_
  _SLACK - Contact us on our public Slack channel_
- [x] Delete `Contact Us` page

**Comment by nicolevasilevsky** [comment]
I did the things I could on this ticket - removing myself now

**Comment by nicolevasilevsky** [comment]
> Make the role of CCDH clearer. That is, add text explaining that the tools we create and the support we provide are NOT directly harmonizing. Rather, we provide the tools and services to empower end users to do so.

I added some text to the top of this page, please let me know if specific revisions are needed:
https://ccdhportaldev.pedscommons.org/node/5

**Comment by nicolevasilevsky** [comment]
It seems unintuitive to me to remove the contact us page- I wouldn't know to go to the concierge page to find the contact info.

**Comment by monicacecilia** [comment]
> It seems unintuitive to me to remove the contact us page- I wouldn't know to go to the concierge page to find the contact info.

@mellybelly asked to please merge `Contact Us` and `Support` (now `Concierge` page). Perhaps she can share some additional perspective.

**Comment by dvenckusuchgo** [comment]
Worked on the remaining items.  I had a question about where to link in the CRDC-H page (/crdc-h).  There is a reference to CRDC in the top paragraph.  That's where I linked it.  If this is incorrect, please let me know.  I'll correct it.  Passing to @monicacecilia for review

**Comment by dvenckusuchgo** [comment]
Deployed to Production
