### ISSUE TITLE
CCDH Website: Update information in 'Team and Organization' page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#48]
URL: https://harmonization.datacommons.cancer.gov/ccdhTeamOrganization

What to do: 
- [x] Update all instances of `Oregon Health and Sciences University` and all instances of `Oregon State University` to `University of Colorado.`
- [x] Update the table of team members to remove: Laura Christopherson, Richard Zhu, Steven Cox, Davera Gabriel 
- [x] Update the table of team members, institutions, and workstreams to: 
  - Add `Christopher Mungall | Lawrence Berkeley National Lab | Tools and Data Quality, Ontology and Terminology`
  - Add `Mark Miller | Lawrence Berkeley National Lab | Tools and Data Quality, Ontology and Terminology`
  - Add `Nomi Harris | Lawrence Berkeley National Lab | Community Development`
  - In the line for Balhoff, add `Tools and Data Quality` to the front of his list of workstreams, and link to it. Similarly, 
  - For Furner, add `Data Model Harmonization` to the front of his list of workstreams. 
  - For McMurry, remove `Data Model Harmonization` from her list of workstreams.
  - For Munoz-Torres, please add `Ontology and Terminology` to the front of my list of workstreams.
  - For Thessen, remove `Data Model Harmonization`
  - For Vasilevsky, add `Community Development` to her list of workstreams. 
  - For Volchenboum, add `Community Development` to his list of workstreams.

**Comment by nicolevasilevsky** [comment]
done - assigning to @dvenckusuchgo for review, thanks!

**Comment by dvenckusuchgo** [comment]
Changes look good.  Passing to @monicacecilia for review.  (For these review tickets, do we want to add a "work completed" or "read to deploy" label?  We can return after everything is pushed to production, confirm the changes, and close the deployed tickets)

**Comment by dvenckusuchgo** [comment]
Deployed to Production
