### ISSUE TITLE
CCDH Website: Update Standards and Tooling Page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#49]
URL: https://harmonization.datacommons.cancer.gov/standardsTooling

What to do: 
- [x] Break out CRDC resources from all other resources
- [ ] Tile the tools on with logos on the tools page (similar to CRDC tools page)
- [ ] Include a few words explaining which nodes have adopted these tools / standards and which are considering.

Please reach out to @mellybelly via email or IM system for details.

**Comment by monicacecilia** [comment]
- [ ] Add how the list is ‘curated’ 
- [ ] Add what users might expect to find here in the future, such as guidance on when to consider using 'which tool' for 'what' 
- [ ] Later on, add recommendations or requirements for use of standards  by the wider CRDC community

(requests from Sherri de Coronado, around 2020/10)

**Comment by gaurav** [comment]
It might make sense to split this content into three pages:
- Standards and tooling built by us: I imagine this as a page with short descriptions of each tool, and with links to the Github repositories or published documentation so readers can use them. The Tools team is [writing up our stuff](https://docs.google.com/document/d/16_HE_2ciDPJstd75ivbUTL22Sez-WGOBA6anT9qUoKM/edit) at the moment, and I think by May 31 we're planning to have the CCDH Terminology Harmonization API up as well. So this will start as a list of 3-5 products that will end up being a list of 5-10 major products that we've built.
- Standards and tooling that we recommend: the [page we currently have with a list of resources that we recommend](https://ccdhportaldev.pedscommons.org/standardsTooling). We'd have to change this page as per Sherri's suggestions -- I've started writing [an improved description that is hopefully clearer](https://docs.google.com/document/d/1qj6TDJeXV4aStHEfltYCPq8tgL41MgTtfmpHIcpoIRM/edit).
- Standards and tooling currently in use: a big summary table listing which CRDC participant uses which tools, based on the interviews we did in 2019-20 and the e2e report, with CRDC participants opening Github issues to update this as things change. We could have some generic columns here as well: for instance, "*New Data Commons*", with our recommendations for what technologies a new data commons should adopt.

What do you all think?

@monicacecilia I'm not sure which "CRDC tools page" you're referring to in the original issue -- could you please add a link? Thanks so much!

**Comment by nicolevasilevsky** [comment]
@gaurav this is the page:
https://harmonization.datacommons.cancer.gov/additional-resources

**Comment by nicolevasilevsky** [comment]
I like your proposed changes @gaurav. Do you want to move forward with this or do you want to wait for approval from @monicacecilia? She' back next week. I think the goal is to have these changes in by the May 31 deliverable

**Comment by gaurav** [comment]
Thanks, Nicole! Here's the current status:
* Standards and tooling built by us: we've finished a [write-up of two of the components we're currently building](https://docs.google.com/document/d/16_HE_2ciDPJstd75ivbUTL22Sez-WGOBA6anT9qUoKM/edit). I've started writing up the third component I've been working on; I think it should be done in a day or two.
* Standards and tooling that we recommend: thanks for the comments on my [improved description](https://docs.google.com/document/d/1qj6TDJeXV4aStHEfltYCPq8tgL41MgTtfmpHIcpoIRM/edit). @monicacecilia Do you think this is good enough for the website? Or is there something more that we need?
* Standards and tooling currently in use: this is going to be a bigger task, presumably based on the CRDC-H interviews from 2019-20 and the end-to-end analysis from earlier this year. Would something like [this spreadsheet](https://docs.google.com/spreadsheets/d/1UtOglFIv_cAXDnH8KExfJ4ApyJe4vWRZ4LWqSdGSnXg/edit#gid=0) make sense? Feel free to edit the spreadsheet extensively if anybody has a better idea about how to do this!

**Comment by gaurav** [comment]
All three of the Tools team components have [now been summarized](https://docs.google.com/document/d/16_HE_2ciDPJstd75ivbUTL22Sez-WGOBA6anT9qUoKM/edit) for the website.

**Comment by gaurav** [comment]
For the "Standards and tooling currently in use", we could add some text to https://harmonization.datacommons.cancer.gov/additional-resources to indicate which of these standards are currently being used in CRDC nodes. Would that be useful?

**Comment by monicacecilia** [comment]
Thank you all for your comments and suggestions. 

Given the time we have, I propose that we:
- keep this page and create one additional page (see #43 and #46). 
- Update the 'Additional Resources' page (formerly 'Standards and tooling' with this text from Gaurav: 
  - ```The CCDH aims to provide relevant standards and tooling for the CRDC community. To do this, we rely on a number of useful standards and tools developed for use in data harmonization, aggregation, modeling and other use cases outside of the CCDH team, which we list below. This list was compiled by CCDH project members and is reviewed and updated regularly. Documentation for each of the resources can be found in the links provided. Please do not hesitate to contact us with any questions relating to these resources, or to send us your questions about ontologies, standards or tooling not already covered in this list.```
  - In the above paragraph, link the  ```contact us``` to the Concierge page at /concierge
- For Phase III, let's work on updating the 'Additional Resources' page with information about usage and our recommendations as Sherri suggested. 

@gaurav @dvenckusuchgo 👀 ⬆️

**Comment by dvenckusuchgo** [comment]
Completed for Phase 2

**Comment by monicacecilia** [comment]
So brilliant! Thank you!! 🌷

**Comment by monicacecilia** [comment]
:bowtie:
