### ISSUE TITLE
CCDH Website: Update the 'About' page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#50]
URL: https://harmonization.datacommons.cancer.gov/about

What to do: 
- [x] Bundle all sub-menu items under the TopLevel Menu `About` into sections within the same web page. Make sure this page is linked from the TopLevel Menu `About.`
- [x] Remove the `CRDC Ecosystem` submenu item from the list. 
- [x] Add text at the bottom of the page that notes `CCDH is part of the NCI Cancer Research Data Commons (CRDC) ecosystem, a cloud-based data science infrastructure that provides secure access to a large, comprehensive, and expanding collection of cancer research data.` Link the words `NCI ... (CRDC)` to https://datacommons.cancer.gov/ and include a linkout icon next to the text to note 'external' content.
- [x] Remove the Project Timeline page, and move its contents to a section in the `About` page. Reduce number of words in the Timeline, and provide linkouts (add `target='blank'` and 'external page' icon)  to pages detailing work in progress where appropriate. For example, linkout the word `CRDC-H` to https://cancerdhc.github.io/ccdhmodel/

**Comment by dvenckusuchgo** [comment]
@monicacecilia Any guidance on the order of the subsections of the "About CCDH" page?  Should it follow the menu order?

**Comment by monicacecilia** [comment]
- Yes, it should follow the menu order. 
- Please update to two submenu items: 1) About ; 2) CCDH Team and Organization
- The rest gets consolidated into one page. 

Thank you! 🌷

**Comment by dvenckusuchgo** [comment]
Revisions completed.

**Comment by monicacecilia** [comment]
Thank you @dvenckusuchgo - just found a tiny, tiny bit to update. 
On the list of institutions at the top of the 'About' page, could I kindly ask that you please take out: 
- Oregon State University
- Oregon Health & Science University
And add: 
- University of Colorado

Thank you! 🌷

**Comment by dvenckusuchgo** [comment]
Revisions to list of institutions completed

**Comment by monicacecilia** [comment]
Thank you!! 😄  🌷 
:bowtie:
