### ISSUE TITLE
CCDH Website: Add 'Contact Us' link to the footer

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#51]
- [ ] Add a link to the new `Contact Us` page from the footer. The URL for that page will be `https://harmonization.datacommons.cancer.gov/contact`

**Comment by dvenckusuchgo** [comment]
Which style is preferred for adding the additional 'Contact Us' link in the footer?
[variation #1](https://drive.google.com/file/d/1RPpmc7GWtAhMZR_yfKomKNQJO0tgN6e5/view?usp=sharing)
[variation #2](https://drive.google.com/file/d/1_XQOnamR7pNTotXuMsx0cUVTnPvF9FZH/view?usp=sharing)
[variation #3](https://drive.google.com/file/d/1gPKasLSCL5IOc85BcBBBiNwQj_AN7os8/view?usp=sharing)
[variation #4](https://drive.google.com/file/d/1lDdVHM1pGS-pCJq63pXguoHdE3IwiPEV/view?usp=sharing)

**Comment by dvenckusuchgo** [comment]
Let's go with [variation #1](https://drive.google.com/file/d/1RPpmc7GWtAhMZR_yfKomKNQJO0tgN6e5/view?usp=sharing)

**Comment by monicacecilia** [comment]
Yes, [variation #1](https://drive.google.com/file/d/1RPpmc7GWtAhMZR_yfKomKNQJO0tgN6e5/view) works; please let's make sure to link the words ```Contact CCDH``` to this page: https://ccdhportaldev.pedscommons.org/concierge

**Comment by dvenckusuchgo** [comment]
Change made to footer template in code.  Committed to [ccdhwebportal-33](https://github.com/CBIIT/ccdhwebportal/issues/33)
