### ISSUE TITLE
CCDH Website: Update 'FAQs' page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#52]
- [x] Link the answer for _"When will this be ready?”_ to the 'About' page section with the timeline.
- [x] Add new questions and answers such as: 
  - What is data harmonization? --> refine a couple paragraphs for an answer with help from @volcs0, @cgchute, @mellybelly 
  - How can nodes learn more about CRDC-H? --> link to CRDC-H documentation within CCDH website
  - How is CCDH using terminologies?
  - What is LinkML? --> Add a small paragraph and link to presentations and documentation materials
  - What is the best way to engage with CCDH?  --> link to Contact Us
  
  @mellybelly, @gaurav, @jiaola, @hsolbrig, @volcs0, @cgchute - could you please help us formulating a few more of these?

**Comment by dvenckusuchgo** [comment]
Changes to content made.  Passing to @monicacecilia for review

**Comment by dvenckusuchgo** [comment]
Deployed to Production
