### ISSUE TITLE
CCDH Website: Home page restyling

### ISSUE THREAD

**Issue by dvenckusuchgo** [cancerDHC/community-development#57]
I was told the the ccdh web portal inherits its style from [https://datacommons.cancer.gov](https://datacommons.cancer.gov).  In comparing the two sites, It's apparent [https://ccdhportaldev.pedscommons.org](https://ccdhportaldev.pedscommons.org) needs more "art" on the home page.  There are some nice design elements on datacommons that we could allude to on ccdh web portal.  Such as...

- Top text on left with image on right [Top](https://drive.google.com/file/d/1r66X2Zh0uDFUntVEs5TXm-V-0CAy1umg/view?usp=sharing)
- mid-page full-width angled image [Mid-page image](https://drive.google.com/file/d/1RbXyYGF8KK4yNPGwLMn4n9f-30ZKb53L/view?usp=sharing)
- Resource listings toward lower part of page [Resources](https://drive.google.com/file/d/153dCFuTKbISYtJQiN4pGirOWYhJielY1/view?usp=sharing)

Is this type of styling we would like to consider?

**Comment by nicolevasilevsky** [comment]
I love all of these ideas!

**Comment by dvenckusuchgo** [comment]
Incorporate graphic elements from 3 points as suggested by Moni https://github.com/cancerDHC/community-development/issues/45#issuecomment-847343249

**Comment by dvenckusuchgo** [comment]
Draft version of restyled homepage now in place for review.  Please share your thoughts.

**Comment by nicolevasilevsky** [comment]
upon first glance, it looks great!

**Comment by dvenckusuchgo** [comment]
Thank you!

D

From: Nicole Vasilevsky ***@***.***>
Reply-To: cancerDHC/community-development ***@***.***>
Date: Tuesday, June 8, 2021 at 10:15 AM
To: cancerDHC/community-development ***@***.***>
Cc: Debra Venckus ***@***.***>, Assign ***@***.***>
Subject: Re: [cancerDHC/community-development] CCDH Website: Home page restyling (#57)
Resent-From: ***@***.***>
Resent-Date: Tuesday, June 8, 2021 at 10:15 AM


upon first glance, it looks great!

**Comment by dvenckusuchgo** [comment]
As we discussed, here are the screenshots of the front page for each site for comparison and comment.

**Current**
- [Current Design - Desktop](https://drive.google.com/file/d/1SSdkRt4XTBeFuM38lE1_p5cupdkPt726/view?usp=sharing)
- [Current Design - Mobile](https://drive.google.com/file/d/1uoulS9jSgnwXZrZzhTx5lUcNu8GVTKkT/view?usp=sharing)

**Proposed**
- [Proposed Design - Desktop](https://drive.google.com/file/d/11v6eNicUg54PTYdqfeKPp_EAfjiTHkhK/view?usp=sharing)
- [Proposed Design - Mobile](https://drive.google.com/file/d/1gFt1WJqbQ8igUur1RmDzITQTrZNA_Ycz/view?usp=sharing)

**Data Commons - Reference**
This is the Data Commons site we try to emulate.
- [Data Commons - Desktop](https://drive.google.com/file/d/1qtrFJkW-ILkfc4-S2xoVCjWHKRgaxQhY/view?usp=sharing)
- [Data Commons - Mobile](https://drive.google.com/file/d/1YvhdoihiKfmm1MgdE9-l_vNIFI9qEbaz/view?usp=sharing)
