### ISSUE TITLE
CCDH Website: Add a Glossary

### ISSUE THREAD

**Issue by dvenckusuchgo** [cancerDHC/community-development#58]
Seems like it would be very useful to add a glossary of terms that can be linked to from other pages.

I will be setting up the page/menu structures for this.  Please share terms & definitions that should be included.

**Comment by nicolevasilevsky** [comment]
Here some terms we could add:
- **controlled vocabulary**: A way to organize knowledge for subsequent retrieval. They are used in subject indexing schemes, subject headings, thesauri, taxonomies and other knowledge organization systems. Controlled vocabulary schemes mandate the use of predefined, authorised terms that have been preselected by the designers of the schemes, in contrast to natural language vocabularies, which have no such restriction. source: https://en.wikipedia.org/wiki/Controlled_vocabulary
- **ontology**: A knowledge classification of a domain, where the relationships between concepts are formally defined and logically related, which allows for computational reasoning (source: PMID:30304648)

**Comment by monicacecilia** [comment]
Here's a [spreadsheet we have in our Internal CCDH folder](https://docs.google.com/spreadsheets/d/1B0f1rE5SAkPfOsE0M22QWTDx-z3_gkLvJn6AyVltco0/edit#gid=1364170751).

**Comment by dvenckusuchgo** [comment]
I have set up the Glossary view page settings, vocabulary and menu links.  Glossary terms are added through the Glossary vocab https://ccdhportaldev.pedscommons.org/admin/structure/taxonomy/manage/glossary/add.  I have not added the terms from the spreadsheet yet, but it's on my radar.

**Comment by dvenckusuchgo** [comment]
The main glossary structures are in place.  Moving the task of adding the terms from the spreadsheet into it's own ticket gh-61

**Comment by monicacecilia** [comment]
Dear @dvenckusuchgo: 
- let's please update the submenu to ```Glossary and Acronyms```
- remember to check on possible bug that's impeding alphabetic sorting

**Comment by monicacecilia** [comment]
@dvenckusuchgo completed all of this. 
:bowtie:
