### ISSUE TITLE
[bug] link to ICD is broken

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#59]
**Description of bug**
should be replaced with https://www.who.int/standards/classifications/other-classifications/international-classification-of-diseases-for-oncology

**Website/URL (if applicable)**
https://harmonization.datacommons.cancer.gov/additional-resources

**Operating system and/or browser (if applicable)**
For example: Mac OS/Chrome
Mac/Chrome

**Comment by dvenckusuchgo** [comment]
Link corrected for ICD-O in Additional Resources grid

**Comment by monicacecilia** [comment]
:bowtie:
