### ISSUE TITLE
[bug] remove ERO from standards list

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/community-development#60]
**Description of bug**
ERO is no longer developed, we shouldn't be promoting it.

**Website/URL (if applicable)**
https://harmonization.datacommons.cancer.gov/additional-resources

**Comment by dvenckusuchgo** [comment]
ERO removed from the Additional Resources grid.
- eagle-i Resource Ontology
- http://bioportal.bioontology.org/ontologies/ERO
- ERO
- ERO models research resources such instruments. protocols, reagents, animal models and biospecimens. It was developed in the context of the eagle-i project.

**Comment by monicacecilia** [comment]
Thank you @dvenckusuchgo ! :bowtie:
