### ISSUE TITLE
CCDH Website Add Glossary Terms

### ISSUE THREAD

**Issue by dvenckusuchgo** [cancerDHC/community-development#61]
Here's a [spreadsheet we have in our Internal CCDH folder](https://docs.google.com/spreadsheets/d/1B0f1rE5SAkPfOsE0M22QWTDx-z3_gkLvJn6AyVltco0/edit#gid=1364170751).

_Originally posted by @monicacecilia in https://github.com/cancerDHC/community-development/issues/58#issuecomment-842506528_

**Comment by monicacecilia** [comment]
Dear @dvenckusuchgo - let's use the acronyms in the 'CCDH view' tab, [here](https://docs.google.com/spreadsheets/d/1B0f1rE5SAkPfOsE0M22QWTDx-z3_gkLvJn6AyVltco0/edit#gid=438806648).

**Comment by nicolevasilevsky** [comment]
@dvenckusuchgo @monicacecilia I added all of the abbreviations in the spreadsheet to drupal

**Comment by dvenckusuchgo** [comment]
Sorting and paging have been added.  More styling is needed, but that will come in a follow up release

**Comment by monicacecilia** [comment]
This is brilliant. Thank you both! 🌷 
I'm calling this 'cooked' - :bowtie:
