### ISSUE TITLE
CCDH Website: Add "Guidelines for professional behavior" link to FAQ

### ISSUE THREAD

**Issue by nlharris** [cancerDHC/community-development#62]
Reminder to add something to the FAQ about "Guidelines for professional behavior" (as described in Support Service and Engagement Plan)

**Comment by monicacecilia** [comment]
Dear @dvenckusuchgo, please let's add this entry to the FAQ: 

Question: ```Does the CCDH team observe a Code of Conduct?```

Answer: ```Yes. To encourage professional interactions at all levels, all members of CCDH, and all members of the community interacting with our team must agree to observe guidelines for professional behavior that encourages a respectful and collegiate environment. The Leidos Code of Conduct [linkto: https://www.leidos.com/sites/g/files/zoouby166/files/2020-11/PDF-Leidos-Code-of-Conduct.pdf] for FNL employees, which governs their engagement with contractors, as well as guidelines from NCI’s Ombuds office and the NIH Ethics Manual [linkto: https://policymanual.nih.gov/2400-01#B34F13F0] (2400 series of NIH manual) serve as the de facto Code of Conduct for interactions with CCDH.```

**Comment by dvenckusuchgo** [comment]
Code of Conduct FAQ added

**Comment by monicacecilia** [comment]
:bowtie:
