### ISSUE TITLE
CCDH Website: Add definition for 'data harmonization' and explanation of 'how CCDH uses terminologies' to the FAQ

### ISSUE THREAD

**Issue by nlharris** [cancerDHC/community-development#63]
reminder to add definition of data harmonization and explanation of how ccdh is using terminologies to the FAQ.

**Comment by monicacecilia** [comment]
Dear @bfurner, kindly asking for some pointers to where we could find some description about what 'Data Harmonization' is (in a general sense) - for the FAQ page. @keblumhardt, perhaps we could grab some text from the presentation Melissa and Sam gave during the _Homing in on Harmonization_ session and see if Brian can work from there?

**Comment by monicacecilia** [comment]
Dear @jiaola, kindly asking for assistance answering the question: "How does CCDH use terminologies?" for the FAQ.

**Comment by monicacecilia** [comment]
- WRT 'data harmonization' - let's take some text from the HioH session and link to the slides.

**Comment by monicacecilia** [comment]
New FAQ: 

Question: ```What is Data Harmonization?```

Answer: ```Data harmonization is a process that aims to achieve alignment and concordance among multiple data sets such that equivalent data elements (e.g. 'tissue_or_organ_of_origin' and 'primary_disease_site') are represented in an equivalent manner (i.e. using the same value set). This facilitates tasks such as query, retrieval, and aggregation across data sets.  More information on this broad topic can be found in the slides we presented during a Homing in on Harmonization session. Slides are available here [linkto: https://docs.google.com/presentation/d/1P74I9ThySG33JSpYOQMFaDyPUt3QEfu7J9nsxX2fiVI/edit#slide=id.gd59e7134fc_0_0].```

**Comment by dvenckusuchgo** [comment]
FAQ revision completed.
