### ISSUE TITLE
CCDH Website: Update linkout for Top Level Menu 'FAQs' and title for submenu 'Glossary'

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#64]
**Description of bug**
1. The top level menu 'FAQs' goes to a _'Page not found'_ error. It wrongly directs the user to /faqs when it should be sending users to /faq (without the 's' at the end). Please update.

2. Please update the title of the submenu item ```Glossary``` to ```Glossary and Acronyms``` as you did for the page header in /glossary

**Website/URL (if applicable)**
/faqs
/glossary

**Operating system and/or browser (if applicable)**
Mac OS/Chrome

Thank you @dvenckusuchgo !! 🌷

**Comment by dvenckusuchgo** [comment]
Fixed.

**Comment by monicacecilia** [comment]
Thank you! 🌷 

:bowtie:
