### ISSUE TITLE
CCDH Website: Add explanation of 'how CCDH uses terminologies' to the FAQ

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#65]
**Description:**
Please add explanation about 'how CCDH uses terminologies' to the FAQ
Leftover from #63

**Website/URL (if applicable)**
https://ccdhportaldev.pedscommons.org/faq

**Comment by dvenckusuchgo** [comment]
I can't seem to find the Answer text for "how CCDH uses terminologies".  I that content we're still waiting on?

**Comment by monicacecilia** [comment]
Yes, we are still waiting on this.

**Comment by dvenckusuchgo** [comment]
I unpublished this specific FAQ Q/A for deployment.  If we get the content later, I can manually add it on the production site and re-publish that bit.

**Comment by hsolbrig** [comment]
Apologies - didn't realize it was that urgent.   Just need to consult w/ Dazhi before I finish it up... sorry

**Comment by hsolbrig** [comment]
CCDH uses terminologies to define and validate the classes, properties and, where appropriate, enumerated values in the models.  As an example, the GDC class, `Analyte` references the NCIt concept [Specimen](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C19157).  The `analyte_type` property references a a characteristic that is applicable to `Specimen`, [Type](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C25284).  In this context, the range of the Type property will include an enumeration of possible analyte types, which would include [FFPE DNA](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C156435), [FFPE RNA](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C156436), [Nuclei RNA](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C174108), etc.  

We will be using an augmented and extended version of the NCIt (NCIt+), which will a) provide a bridge between the core NCI Thesaurus concept codes and their corresponding entries in external ontologies and b) included additional formal definitions where needed.

NCIt+ elements will include additional information, including:

* Complete definitions of compositional structures that occur in the caDSR today.  As an example, the caDSR currently links `Analyte` above to two NCIT codes -- [Specimen](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C19157) and [Molecular](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C25574), but does not formally assert the relationship between these two concepts.  The NCIt+ will contain a newly minted concept identifier for `Molecular Specimen` that formally defines what it means for a specimen to be "molecular".
* range definitions and range memberships -- a new concept identifier that defines what a "Type" is in the context of a "Molecular Specimen".  The domain of this new "Molecular Specimen Type" will include a (partial) list of possible types, which would include  FFPE DNA, FFPE RNA, Nuclei RNA amongst others.   This range can be used in both validation and mapping tasks.  In the current model, for instance,  these are all types of [Biospecimen](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C70699), which would appear to be overarching range of `analyte_type`.  Interestingly, however, one of the current analyte_type values, [DNA](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C449) is _not_ a subclass of Biospecimen, which indicates that either a) it is not a valid analyte_type or b) the NCIt (+) has an incomplete categorization.

Terminology is also used for aligning and validating models with different granularities.  As an example, some parts of the GDC model use a single concept identifier in the analyte_type code set identifier to identify a sample that is a) DNA and b) is preserved via. Formalin-Fixed Paraffin-Embedding.  In other cases, however, we find situations where these two characteristics have been separated and the molecular type (DNA) and perservation method(FFPE) occur as separate attributes.  Definitions must be incorporated into the NCIt+ that allow one to use the definition of FFPE DNA to tease out the two separate facts and, where necessary, roll the two components up as needed.

**Comment by monicacecilia** [comment]
@dvenckusuchgo - we have an answer to add to our FAQ. 
May I kindly ask that you post this content and re-publish when appropriate? THANK YOU! 🌷

**Comment by dvenckusuchgo** [comment]
FAQ updated and published on both ccdhportaldev and production.

**Comment by monicacecilia** [comment]
THANK YOU @dvenckusuchgo!! 🌷 

THANK YOU @hsolbrig!! 🌷
