### ISSUE TITLE
CCDH Website: Update title for community interactions SOP page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#69]
**Description of request:**
Please update current title `SOP for Interactions with NCI Data Nodes` to `Standard Operating Procedure for Interaction with NCI Data Nodes` 

**Website/URL:**
https://harmonization.datacommons.cancer.gov/community-interactions

Thank you, and sorry to pester. 🌷

**Comment by dvenckusuchgo** [comment]
Fixed.

**Comment by monicacecilia** [comment]
Thank you! I see it on staging but not in production yet, so I'll keep it open until we make that last push to production.

**Comment by dvenckusuchgo** [comment]
Fixed on Production

**Comment by monicacecilia** [comment]
Thank you! :bowtie:
