### ISSUE TITLE
CCDH Website: Update figure in landing page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#70]
**Description:**
Please update current figure at https://harmonization.datacommons.cancer.gov/ with new image created on 5/28 (sent you link on Slack).

**Comment by dvenckusuchgo** [comment]
Image updated (Production & ccdhportaldev)

**Comment by monicacecilia** [comment]
Thank you! 
This update is brilliant! :) 
May I kindly ask if you could please remove this new image from the /ccdh-resources page, though? (see my note in the source doc if you need more details). 

THANKS!  🌷

**Comment by dvenckusuchgo** [comment]
Image removed from top of /ccdh-resources
