### ISSUE TITLE
CCDH GitHub Pages: Update landing page

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/community-development#71]
**Description:**
Please update content at https://cancerdhc.github.io/ with material from CCDH Resources Google document (link on Slack). 
Also, at the top, please add figure created on 5/28 (link on Slack), with the following title: 

- **Figure:** The role of CCDH in the wider CRDC environment.

Thank you!

**Comment by monicacecilia** [comment]
@jen-martin, @mellybelly has requested to please add navigation to `/dashboard` and `/terminology` from the landing page. 

Is it possible to add a navigation bar on the left, that captures subsections in the landing page (more or less the way an 'outline' shows up on a Google doc (screenshot with example below), or the navigation headers in ReadTheDocs ([example here](https://cancerdhc.github.io/ccdhmodel/v0.2/))? 

<img width="282" alt="Screen Shot 2021-05-29 at 2 35 02 PM" src="https://user-images.githubusercontent.com/1714621/120085648-ce105d00-c08e-11eb-8084-c027edab0090.png">

**Comment by monicacecilia** [comment]
Dear @jen-martin, 
@mellybelly has a few more requests, some for the landing page, and some for a new page. Thank you very much in advance for your flexibility. 🌷 

---------

- [ ] please create a new markdown page, `/ccdh-resources` 
   - [ ] please move the text currently on http://cancerdhc.github.io/ (that is, the text you extracted from the google doc) to this new page, starting with the text from the section entitled `Harmonized CRDC Data Model (CRDC-H)` all the way through the end of the page.  Do not move the figure and figure legend at the top of the current landing page to the new `/ccdh-resources`  page. That figure should stay in the landing page (see below).
   - [ ] please add a title to the page: `CCDH Resources`
   - [ ] in this new page, please create a navigation or browsing mechanism to allow users to navigate through subsections in this page. This can be, for example, something along the lines of an 'outline' in a Google doc (screenshot with example below), and adding with links to each subsection; or it could be as it appears in the navigation bar in a ReadTheDocs  page ([example here](https://cancerdhc.github.io/ccdhmodel/v0.2/))? 
   - <img width="282" alt="Screen Shot 2021-05-29 at 2 35 02 PM" src="https://user-images.githubusercontent.com/1714621/120085648-ce105d00-c08e-11eb-8084-c027edab0090.png">

---------

- in the landing page: 
  - [ ] please emulate the contents of the landing page at https://harmonization.datacommons.cancer.gov; that is, keep the current figure and legend, and replace all the text that has now moved to the new page with the following text (before the figure):
     - `The CCDH serves three main roles within the Cancer Research Data Commons (CRDC) ecosystem:`
        - `Facilitate retrospective and prospective semantic harmonization of data across nodes of the CRDC.`
        - `Coordinate the community to ensure quality “fit for purpose” design and implementation of standards that will facilitate interoperability of heterogeneous data types and CRDC resources`
        - `Find agreement across the communities built around CRDC, including matching and extending data models, determining annotation and harmonization and building quality assurance resources.` 
  - [ ] please ensure users can navigate to to `/dashboard` and `/terminology` and `/ccdh-resources` from the landing page.

**Comment by mellybelly** [comment]
This looks perfect in terms of organization, thanks for reading my mind while i was in transit. @jen-martin let me know if you have any questions or suggestions.

**Comment by monicacecilia** [comment]
Please update third bullet point to: 
- `Find agreement across the CRDC community, determining annotation and harmonization needs, and helping to build quality assurance resources that function across the CRDC.`

**Comment by dvenckusuchgo** [comment]
Updated text for 3rd bullet point on home page. (Production + ccdhportaldev)

**Comment by monicacecilia** [comment]
@jen-martin - this is looking brilliant! 🎉 
- Is there any chance we could please add links like those at the top of the landing page to the `/ccdh-resources` and '/terminology' pages as well, so users can navigate to the other pages?
- Alternatively, a `Home` button so people can navigate back?

**Comment by jen-martin** [comment]
I added a table with a navigation menu to the top of the home page, ccdh-resources, and terminolgy pages:
Home | CCDH Resources | Terminology and Ontology Workstream | Project Task Dashboard

**Comment by jen-martin** [comment]
This should be complete! Let me know if there should be any other additional modifications/edits

**Comment by monicacecilia** [comment]
@jen-martin please see @mellybelly's requests from the last few minutes in comm-dev Slack. 🌷
