### ISSUE TITLE
Add Homing in on Harmonization sessions to website

### ISSUE THREAD

**Issue by keblumhardt** [cancerDHC/community-development#73]
Please add the following information to the "Concierge" page of the website:

[under past]
Title: [Foundations of Data Harmonization](https://docs.google.com/presentation/d/1l0pjEemw8V2Sleh41yohz7FnfELbHxyeiRmwjQaWE8o/edit#slide=id.ge0868dd016_0_0) (slides)
Summary: A continuation from the first Homing in on Harmonization session.
Recording: Foundations of Data Harmonization (multimedia) @monicacecilia 
Presenters: Chris Chute
Date: June 26, 2021

[under upcoming]
Title: Session # 3
Presenters: tbd
Date: August 26, 2021

Title: Session # 4
Presenters: tbd
Date: October 28, 2021

Title: Session # 5
Presenters: tbd
Date: December 30, 2021

**Comment by dvenckusuchgo** [comment]
Omitting "Recording:" until we have the link.

**Comment by keblumhardt** [comment]
@monicacecilia can you add the recording to this ticket when you are able? Thank you!!

**Comment by monicacecilia** [comment]
I shared the link via email with both of you. 🌷

**Comment by dvenckusuchgo** [comment]
Recording link added to Staging and Production
