### ISSUE TITLE
Concierge page updates

### ISSUE THREAD

**Issue by keblumhardt** [cancerDHC/community-development#74]
Please make the following updates to the concierge page:

- [x] Add pdf for July Newsletter
[CCDH Update - July 2021.pdf](https://github.com/cancerDHC/community-development/files/6970830/CCDH.Update.-.July.2021.pdf)

- [x] Remove session # 3 of Homing in on Harmonization sessions and re-number. (there will be no meeting in August)

Thank you!

**Comment by dvenckusuchgo** [comment]
Updated on Staging/Sandbox and Production sites.
