### ISSUE TITLE
Summit with the CDA team

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/community-development#9]
- [x] Determine the ideal time window for our CCDH team to meet
- [x] Send this availability to the CDA team (TBD once it is awarded)
- [x] Set agenda and required staff for the meeting
- [x] Set location and logistics for the meeting
- [x] Document resulting decisions and action items
~~- [ ] Get advance travel approvals from FNL~~
~~- [ ] Get reimbursements cooking~~

**Comment by nicolevasilevsky** [comment]
@keblumhardt can this be closed?
